### obtener todos los productos
GET http://localhost:3000/api/productos

### obtener un producto en particular
GET http://localhost:3000/api/productos/55

### crear nuevo producto
POST http://localhost:3000/api/productos
Content-Type: application/json

{
    "codigo": "60",
    "nombre": "Crema de enjuague BB+",
    "stock": 26
}

### modificar un producto (PUT)
PUT http://localhost:3000/api/productos/55
Content-Type: application/json

{
    "codigo": "55",
    "nombre": "Aceite de Almendra",
    "stock": 8
}

### modificar un producto (PATCH)
PATCH  http://localhost:3000/api/productos/55
Content-Type: application/json

{
    "nombre": "Protector Solar"
}

### borrar un producto
DELETE http://localhost:3000/api/productos/55