###Obtener todas las localidades
GET http://localhost:3000/api/localidades

###Obtener una localidad
GET http://localhost:3000/api/localidades/6

###Dar de alta una Localidad
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombre": "Calamuchita",
    "provincia": "Cordoba",
    "codigo_postal": "2578",
    "pais": "Argentina",
    "descripcion": "Capital de la sierra"
}

###Actualizar localidad
PUT http://localhost:3000/api/localidades/11
Content-Type: application/json

{
    "codigo_postal": "2577"
}

###Eliminar localidad
DELETE http://localhost:3000/api/localidades/12