### obtener todos los clientes
GET http://localhost:3000/api/clientes

### obtener un cliente
GET http://localhost:3000/api/clientes/2

### crear cliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "dni": "45314899",
    "NomyApe": "Pedro Ferramondo",
    "direccion": "Calle A 23",
    "email": "pferramondo22@gmail.com",
    "telefono": 2477123456,
    "codigo_localidad": 7,
    "password": "Aa45521!adf"
}

### modificar cliente (PUT)
PUT http://localhost:3000/api/clientes/12
Content-Type: application/json

{
    "dni": "98765491",
    "NomyApe": "Agustin Raggi",
    "direccion": "Brandsen 805",
    "email": "arielitoElMagnifico@gmail.com",
    "telefono": "2044785658",
    "codigo_localidad": 8,
    "password": "Aa45521!adf"
}

###Borrar un Cliente
DELETE http://localhost:3000/api/clientes/3