### obtener todos los clientes
GET http://localhost:3000/api/clientes

### obtener un cliente
GET http://localhost:3000/api/clientes/2

### crear cliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "dni": "889944559",
    "NomyApe": "Carlos Potmop",
    "direccion": "Calle A 23",
    "email": "carlitos@example.com",
    "telefono": 2477123456,
    "codigo_localidad": 1
}

### modificar cliente (PUT)
PUT http://localhost:3000/api/clientes/12
Content-Type: application/json

{
    "dni": "98765491",
    "NomyApe": "Agustin Raggi",
    "direccion": "Brandsen 805",
    "email": "arielitoElMagnifico@gmail.com",
    "telefono": "2044785658",
    "codigo_localidad": 8
}

###Borrar un Cliente
DELETE http://localhost:3000/api/clientes/3