### obtener todos los turnos
GET http://localhost:3000/api/turnos

### obtener un turno
GET http://localhost:3000/api/turnos/1

### crear turno
POST http://localhost:3000/api/turnos/3
Content-Type: application/json

{
    "codigo_peluquero": 1,
    "codigo_cliente": 2,
    "fecha_hora": "2010-05-13T16:00:00.000Z",
    "tipo_turno": "Sucursal",
    "porcentaje": 0,
    "estado": "Activo"
}

###Modificar un turno (PUT)
PUT http://localhost:3000/api/turnos/3
Content-Type: application/json

{
    "codigo_peluquero": 1,
    "codigo_cliente": 3,
    "fecha_hora": "2010-05-14T16:00:00.000Z",
    "tipo_turno": "A domicilio",
    "porcentaje": 25,
    "estado": "Incactivo"
}

### modificar Turno (PATCH)
PATCH  http://localhost:3000/api/turnos/3
Content-Type: application/json

{
    "codigo_peluquero": 1,
    "codigo_cliente": 3,
    "fecha_hora": "2010-05-13T16:00:00.000Z",
    "estado": "Activo"
}

###Borrar un Turno
DELETE http://localhost:3000/api/turnos/3