### obtener todos los peluqueros
GET http://localhost:3000/api/peluqueros

### obtener un peluquero
GET http://localhost:3000/api/peluqueros/1

### crear nuevo peluquero
POST http://localhost:3000/api/peluqueros
Content-Type: application/json

{
    "nombre": "Carlos Rodriguez",
    "fecha_Ingreso": "2008-02-26T00:00:00Z",
    "tipo": "Domicilio"
}

### modificar peluquero (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/peluqueros/2
Content-Type: application/json

{
    "nombre": "Maria Gutierrez",
    "fecha_Ingreso": "2008-02-26T00:00:00Z",
    "tipo": ["Sucursal"]
}

### modificar peluquero (PATCH - recurso PARCIAL)
PATCH  http://localhost:3000/api/peluqueros/2
Content-Type: application/json

{
    "nombre": "Marcelo Tevez"
}

###Borrar un Peluquero
DELETE http://localhost:3000/api/peluqueros/3