### obtener todos los peluqueros
GET http://localhost:3000/api/peluqueros

### obtener un peluquero
GET http://localhost:3000/api/peluqueros/1

### crear nuevo peluquero
POST http://localhost:3000/api/peluqueros
Content-Type: application/json

{
    "nombre": "Mirko Ostoich",
    "fecha_Ingreso": "2017-08-26T00:00:00Z",
    "tipo": "Domicilio",
    "email": "mirkitosti@gmail.com",
    "password": "Ab123456!"
}

### modificar peluquero (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/peluqueros/42
Content-Type: application/json

{
    "tipo": "Sucursal"
}

###Borrar un Peluquero
DELETE http://localhost:3000/api/peluqueros/2

### prueba de error
GET http://localhost:3000/api/peluqueros/error-test