### obtener todos los tipos de servicio
GET http://localhost:3000/api/tiposervicio

### obtener un tipo de servicio
GET http://localhost:3000/api/tiposervicio/3

### crear tipo de servicio
POST http://localhost:3000/api/tiposervicio
Content-Type: application/json

{
    "nombre": "Cuidados Capilares",
    "descripcion": "Masaje capilar + hidratacion + alisado",
    "duracion_estimada": 180,
    "precio_base": 36000
}

### modificar un tipo de servicio (PUT)
PUT http://localhost:3000/api/tiposervicio/11
Content-Type: application/json

{
    "duracion_estimada": 150
}

###Borrar un tipo de servicio
DELETE http://localhost:3000/api/tiposervicio/10

### obtener todos los tipos de servicio
GET http://localhost:3000/api/tiposervicio/obtenerMisServicios/3