### obtener todos los tipos de servicio
GET http://localhost:3000/api/tiposervicio

### obtener un tipo de servicio
GET http://localhost:3000/api/tiposervicio/

### crear tipo de servicio
POST http://localhost:3000/api/tiposervicio
Content-Type: application/json

{
    "nombre": "Implante de pelo",
    "descripcion": "Implante + Corte de cabello básico",
    "duracion_estimada": 360,
    "precio_base": 25.00
}

### modificar un tipo de servicio (PUT)
PUT http://localhost:3000/api/tiposervicio/1
Content-Type: application/json

{
    "nombre": "Tintura",
    "descripcion": "Corte de cabello básico + tintura completa",
    "duracion_estimada": 120,
    "precio_base": 45000.00
}

###Borrar un tipo de servicio
DELETE http://localhost:3000/api/tiposervicio/1