### obtener todos los servicios
GET http://localhost:3000/api/servicios

### obtener un servicio
GET http://localhost:3000/api/servicios/9

### crear servicio
POST http://localhost:3000/api/servicios/
Content-Type: application/json

{ 
    "monto": 12000,
    "estado": "Pendiente",
    "ausencia_cliente": "Se presento",
    "medio_pago": "Efectivo",
    "turno_codigo_turno": 47,
    "tipo_servicio_codigo": 3
}

###Modificar un servicio (PUT)
PUT http://localhost:3000/api/servicios/11
Content-Type: application/json

{
    "monto": 9500.00,
    "estado": "Pendiente",
    "ausencia_cliente": "Se presento",
    "medio_pago": "Efectivo",
    "turno_codigo_turno": 18,
    "tipo_servicio_codigo": 3
}

###Borrar un servicio
DELETE http://localhost:3000/api/servicios/9

### Obtener total mensual
GET http://localhost:3000/api/servicios/ingresosMensuales?mes=2024-11

###Buscar el turno asociado al servicio
GET http://localhost:3000/api/servicios/buscarMiTurno/14