### obtener todos los servicios
GET http://localhost:3000/api/servicios

### obtener un servicio
GET http://localhost:3000/api/servicios/1

### crear servicio
POST http://localhost:3000/api/servicios/
Content-Type: application/json

{ 
    "monto": 8000.00,
    "estado": "Activo",
    "adicional_adom": 0,
    "ausencia_cliente": "No",
    "medio_pago": "Mercado Pago",
    "turno": {
    "codigo_turno": 5
    }
}

###Modificar un servicio (PUT)
PUT http://localhost:3000/api/servicios/1
Content-Type: application/json

{
    "monto": 6000.00,
    "estado": "Inactivo",
    "adicional_adom": 0,
    "ausencia_cliente": "No",
    "medio_pago": "Efectivo",
    "turno": {
        "codigo_turno": 8
    }
}

###Borrar un servicio
DELETE http://localhost:3000/api/servicios/3