### obtener todos los servicios
GET http://localhost:3000/api/servicios

### obtener un servicio
GET http://localhost:3000/api/servicios/1

### crear servicio
POST http://localhost:3000/api/servicios/
Content-Type: application/json

{ 
    "monto": 9500.00,
    "estado": "Pendiente",
    "adicional_adom": 0,
    "ausencia_cliente": "Se presento",
    "medio_pago": "Mercado Pago",
    "turno_codigo_turno": 30,
    "tipo_servicio_codigo": 3
}

###Modificar un servicio (PUT)
PUT http://localhost:3000/api/servicios/20
Content-Type: application/json

{
    "monto": 9500.00,
    "estado": "Pendiente",
    "adicional_adom": 0,
    "ausencia_cliente": "Se presento",
    "medio_pago": "Mercado Pago",
    "turno_codigo_turno": 28,
    "tipo_servicio_codigo": 3
}

###Borrar un servicio
DELETE http://localhost:3000/api/servicios/3