### obtener todos los turnos
GET http://localhost:3000/api/turnos

### obtener un turno
GET http://localhost:3000/api/turnos/4

### crear turno
POST http://localhost:3000/api/turnos
Content-Type: application/json

{
    "fecha_hora": "2010-05-13T16:00:00.000Z",
    "tipo_turno": "Sucursal",
    "porcentaje": 0,
    "estado": "Inactivo",
    "codigo_cliente": 7,
    "codigo_peluquero": 1,
    "servicio": 1
}

###Modificar un turno (PUT)
PUT http://localhost:3000/api/turnos/4
Content-Type: application/json

{
    "sanitizedInput": {
        "codigo_peluquero": 8,
        "codigo_cliente": 3,
        "fecha_hora": "2010-05-14T16:00:00.000Z",
        "tipo_turno": "A domicilio",
        "porcentaje": 25,
        "estado": "Incactivo"
    }
}

###Borrar un Turno
DELETE http://localhost:3000/api/turnos/2