### obtener todos los turnos
GET http://localhost:3000/api/turnos

### obtener un turno
GET http://localhost:3000/api/turnos/18

### crear turno
POST http://localhost:3000/api/turnos
Content-Type: application/json

{
    "fecha_hora": "2025-08-04T16:00:00.000Z",
    "tipo_turno": "Sucursal",
    "porcentaje": 0,
    "estado": "Activo",
    "codigo_cliente": 7,
    "codigo_peluquero": 17
}

###Modificar un turno (PUT)
PUT http://localhost:3000/api/turnos/47
Content-Type: application/json

{
    "codigo_peluquero": 17,
    "codigo_cliente": 7,
    "fecha_hora": "2025-08-13T12:00:00.000Z",
    "tipo_turno": "A Domicilio",
    "porcentaje": 25,
    "estado": "Cancelado"
}

###Borrar un Turno
DELETE http://localhost:3000/api/turnos/16

### Filtrar Turnos por fecha
GET http://localhost:3000/api/turnos/filtrados?mes=2024-10

### Filtrar Turnos Cancelados por fecha
GET http://localhost:3000/api/turnos/filtroCancelados?mes=2024-10

### Filtrar Turnos por su estado y peluquero.
GET http://localhost:3000/api/turnos/filtrosTurnoPorEstadoYPel?codigo_peluquero=17&estado=Cancelado
