###Buscar un cliente con el email y la contraseña
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "peluquero1@example.com",
    "password": "Ab123456!"
}

### Obtener clientes con token válido
GET http://localhost:3000/api/clientes
Authorization: Bearer ***REMOVED***.eyJjb2RpZ28iOjE3LCJyb2wiOiJwZWx1cXVlcm8iLCJpYXQiOjE3NDY0MzU5NTYsImV4cCI6MTc0NjQzNjAxNn0.***REMOVED***

### Obtener peluqueros con token válido
GET http://localhost:3000/api/peluqueros
Authorization: Bearer ***REMOVED***.eyJjb2RpZ28iOjE3LCJyb2wiOiJwZWx1cXVlcm8iLCJpYXQiOjE3NDY0MzY3NTksImV4cCI6MTc0NjQ0NzU1OX0.***REMOVED***

### Refresh token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "***REMOVED***.eyJjb2RpZ28iOjE3LCJyb2wiOiJwZWx1cXVlcm8iLCJpYXQiOjE3NDY0MzY2NjksImV4cCI6MTc0NjQ0NzQ2OX0.***REMOVED***"
}